-- Atividade pratica: Implantacao do Modelo Fisico no Oracle APEX
-- Sistema de Vendas e Analise Comercial
-- script de criacao das tabelas (DDL), rodar direto no SQL Commands do APEX

-- rodar isso aqui so se precisar resetar o schema antes de recriar tudo
DROP TABLE tb_auditoria_venda CASCADE CONSTRAINTS;
DROP TABLE tb_venda_item CASCADE CONSTRAINTS;
DROP TABLE tb_venda CASCADE CONSTRAINTS;
DROP TABLE tb_produto CASCADE CONSTRAINTS;
DROP TABLE tb_vendedor CASCADE CONSTRAINTS;
DROP TABLE tb_cliente CASCADE CONSTRAINTS;
DROP TABLE tb_categoria CASCADE CONSTRAINTS;
DROP TABLE tb_calendario CASCADE CONSTRAINTS;

-- tabelas sem FK primeiro

CREATE TABLE tb_cliente (
    id_cliente   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR2(150) NOT NULL,
    email        VARCHAR2(120) NOT NULL,
    cpf          VARCHAR2(11) NOT NULL,
    telefone     VARCHAR2(20),
    dt_cadastro  DATE DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT uq_cliente_email UNIQUE (email),
    CONSTRAINT uq_cliente_cpf UNIQUE (cpf),
    CONSTRAINT ck_cliente_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE tb_vendedor (
    id_vendedor  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR2(120) NOT NULL,
    email        VARCHAR2(120) NOT NULL,
    dt_admissao  DATE DEFAULT SYSDATE NOT NULL,
    ativo        CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT uq_vendedor_email UNIQUE (email),
    CONSTRAINT ck_vendedor_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE tb_categoria (
    id_categoria  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_categoria_nome UNIQUE (nome)
);

-- produto depende de categoria

CREATE TABLE tb_produto (
    id_produto    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria  NUMBER NOT NULL,
    sku           VARCHAR2(30) NOT NULL,
    nome          VARCHAR2(120) NOT NULL,
    preco_unit    NUMBER(12,2) NOT NULL,
    ativo         CHAR(1) DEFAULT 'S' NOT NULL,
    dt_cadastro   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_produto_sku UNIQUE (sku),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES tb_categoria (id_categoria),
    CONSTRAINT ck_produto_preco CHECK (preco_unit > 0),
    CONSTRAINT ck_produto_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE INDEX ix_prod_categoria ON tb_produto (id_categoria);

-- cabecalho da venda, depende de cliente e vendedor

CREATE TABLE tb_venda (
    id_venda        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      NUMBER NOT NULL,
    id_vendedor     NUMBER NOT NULL,
    dt_venda        DATE DEFAULT SYSDATE NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    canal           VARCHAR2(20) NOT NULL,
    valor_bruto     NUMBER(14,2) DEFAULT 0 NOT NULL,
    desconto_total  NUMBER(14,2) DEFAULT 0 NOT NULL,
    valor_liquido   NUMBER(14,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_venda_cliente FOREIGN KEY (id_cliente) REFERENCES tb_cliente (id_cliente),
    CONSTRAINT fk_venda_vendedor FOREIGN KEY (id_vendedor) REFERENCES tb_vendedor (id_vendedor),
    CONSTRAINT ck_venda_status CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA')),
    CONSTRAINT ck_venda_canal CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    CONSTRAINT ck_venda_valor CHECK (valor_liquido >= 0)
);

CREATE INDEX ix_venda_dt ON tb_venda (dt_venda);
CREATE INDEX ix_venda_cliente ON tb_venda (id_cliente);
CREATE INDEX ix_venda_vendedor ON tb_venda (id_vendedor);

-- itens da venda, depende de venda e produto

CREATE TABLE tb_venda_item (
    id_venda_item        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda             NUMBER NOT NULL,
    id_produto           NUMBER NOT NULL,
    quantidade           NUMBER(10) NOT NULL,
    valor_unit           NUMBER(12,2) NOT NULL,
    percentual_desconto  NUMBER(5,2) DEFAULT 0 NOT NULL,
    valor_total          NUMBER(14,2) NOT NULL,
    CONSTRAINT fk_item_venda FOREIGN KEY (id_venda) REFERENCES tb_venda (id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_item_produto FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto),
    CONSTRAINT ck_item_qtd CHECK (quantidade > 0),
    CONSTRAINT ck_item_valor_unit CHECK (valor_unit >= 0),
    CONSTRAINT ck_item_desconto CHECK (percentual_desconto BETWEEN 0 AND 50)
);

CREATE INDEX ix_item_venda ON tb_venda_item (id_venda);
CREATE INDEX ix_item_produto ON tb_venda_item (id_produto);

-- tabelas extras (nao pedidas no enunciado, coloquei a mais)

CREATE TABLE tb_auditoria_venda (
    id_auditoria  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda      NUMBER NOT NULL,
    operacao      VARCHAR2(10) NOT NULL,
    usuario_bd    VARCHAR2(128) NOT NULL,
    dt_evento     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detalhes      VARCHAR2(4000)
);

CREATE TABLE tb_calendario (
    dt_ref            DATE PRIMARY KEY,
    ano               NUMBER(4) NOT NULL,
    mes               NUMBER(2) NOT NULL,
    dia               NUMBER(2) NOT NULL,
    trimestre         NUMBER(1) NOT NULL,
    nome_mes          VARCHAR2(15) NOT NULL,
    dia_semana        NUMBER(1) NOT NULL,
    nome_dia_semana   VARCHAR2(15) NOT NULL
);
